### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by lanpai** [cv-enterprises/linux-help#1]
I think it'd be a lot more human-readable if we split the contents of the README.md into separate files categorized accordingly.

Top-level directories for general categories like "Text Editors", "Compilation", "Navigation", and probably a GettingStarted.md with the README.md giving a table of contents of the whole file structure.

Each directory could then have specifics inside of them "Text Editors" could contain nano.md, vi.md, and vim.md for example.

**Comment by raviriley** [comment]
Good idea, want to submit a pull request?

**Comment by lanpai** [comment]
Sure that sounds good
